# Generated by Django 3.0.8 on 2020-07-30 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Production_line',
            fields=[
                ('line_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('machine_code', models.CharField(max_length=10)),
                ('machine_name', models.CharField(max_length=20)),
                ('machine_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('screen_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('screen_name', models.CharField(max_length=15)),
                ('file_py', models.CharField(max_length=10)),
                ('file_html', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('create_by', models.CharField(max_length=6)),
                ('create_date', models.DateTimeField()),
                ('start_date', models.DateField()),
                ('expired_date', models.DateField()),
                ('expired_day', models.IntegerField()),
                ('update_by', models.CharField(max_length=6)),
                ('update_date', models.DateTimeField()),
                ('last_login_date', models.DateTimeField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Role')),
                ('user_production', models.ManyToManyField(to='Machine_Management.Production_line')),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='role_screen',
            field=models.ManyToManyField(to='Machine_Management.Screen'),
        ),
    ]
