# Generated by Django 3.0.8 on 2020-08-13 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine_type',
            fields=[
                ('mtype_id', models.AutoField(primary_key=True, serialize=False)),
                ('mtype_code', models.CharField(max_length=20)),
                ('mtype_name', models.CharField(max_length=50)),
                ('create_by', models.CharField(max_length=20)),
                ('create_date', models.DateField()),
                ('last_update_by', models.CharField(default=None, max_length=20, null=True)),
                ('last_update_date', models.DateField(default=None, null=True)),
            ],
            options={
                'db_table': 'Machine_type',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('org_id', models.AutoField(primary_key=True, serialize=False)),
                ('org_code', models.CharField(max_length=10)),
                ('org_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Organization',
            },
        ),
        migrations.CreateModel(
            name='Production_line',
            fields=[
                ('productionline_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_site', models.CharField(choices=[('BC', 'บางชัน'), ('CAD1', 'ลาดกระบัง1')], default='BC', max_length=15)),
                ('location_building', models.CharField(max_length=15)),
                ('location_floor', models.CharField(max_length=10)),
                ('production_line', models.IntegerField()),
            ],
            options={
                'db_table': 'Production_line',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Role_management',
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('screen_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('screen_name', models.CharField(max_length=20)),
                ('file_py', models.CharField(max_length=30)),
                ('file_html', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Screen_management',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('create_by', models.CharField(max_length=6)),
                ('create_date', models.DateTimeField()),
                ('start_date', models.DateField()),
                ('expired_date', models.DateField()),
                ('expired_day', models.IntegerField(default=90)),
                ('update_by', models.CharField(default=None, max_length=6, null=True)),
                ('update_date', models.DateTimeField(default=None, null=True)),
                ('last_login_date', models.DateTimeField(default=None, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Role')),
            ],
            options={
                'db_table': 'User_management',
            },
        ),
        migrations.CreateModel(
            name='Role_Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_insert', models.CharField(max_length=5)),
                ('permission_update', models.CharField(max_length=5)),
                ('permission_delete', models.CharField(max_length=5)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Role')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Screen')),
            ],
            options={
                'db_table': 'Role_Screen',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='members',
            field=models.ManyToManyField(through='Machine_Management.Role_Screen', to='Machine_Management.Screen'),
        ),
        migrations.AddField(
            model_name='organization',
            name='org_line',
            field=models.ManyToManyField(to='Machine_Management.Production_line'),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('level', models.IntegerField()),
                ('parent_menu', models.CharField(default=None, max_length=30, null=True)),
                ('index', models.IntegerField()),
                ('path_url', models.CharField(default=None, max_length=30, null=True)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Screen')),
            ],
            options={
                'db_table': 'Menu_management',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_id', models.CharField(default=None, max_length=50, null=True)),
                ('machine_code', models.CharField(default=None, max_length=20, null=True)),
                ('machine_name', models.CharField(default=None, max_length=50, null=True)),
                ('machine_brand', models.CharField(default=None, max_length=10, null=True)),
                ('machine_model', models.CharField(default=None, max_length=10, null=True)),
                ('machine_supplier_code', models.CharField(default=None, max_length=10, null=True)),
                ('machine_location_id', models.CharField(default=None, max_length=10, null=True)),
                ('machine_emp_id_response', models.CharField(default=None, max_length=15, null=True)),
                ('machine_capacity_per_minute', models.CharField(default=None, max_length=10, null=True)),
                ('machine_capacity_measure_unit', models.CharField(default=None, max_length=10, null=True)),
                ('machine_power_use_watt_per_hour', models.CharField(default=None, max_length=10, null=True)),
                ('machine_installed_datetime', models.DateField(default=None, null=True)),
                ('machine_start_use_datetime', models.DateField(default=None, null=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Production_line')),
                ('machine_type', models.ManyToManyField(to='Machine_Management.Machine_type')),
            ],
            options={
                'db_table': 'Machine_master',
            },
        ),
    ]
