# Generated by Django 3.0.8 on 2020-10-08 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Building',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(max_length=20)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Building')),
            ],
            options={
                'db_table': 'Floor',
                'ordering': ['site', 'building', 'floor'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_id', models.CharField(default=None, max_length=50, null=True)),
                ('machine_production_line_code', models.CharField(default=None, max_length=30, null=True)),
                ('machine_name', models.CharField(blank=True, max_length=50)),
                ('machine_brand', models.CharField(blank=True, max_length=50)),
                ('machine_model', models.CharField(blank=True, max_length=50)),
                ('machine_supplier_code', models.CharField(blank=True, max_length=50)),
                ('machine_supplier_name', models.CharField(blank=True, max_length=50)),
                ('machine_supplier_contact', models.CharField(blank=True, max_length=50)),
                ('machine_eng_emp_id', models.CharField(blank=True, max_length=50)),
                ('machine_eng_emp_name', models.CharField(blank=True, max_length=50)),
                ('machine_eng_emp_contact', models.CharField(blank=True, max_length=50)),
                ('machine_pro_emp_id', models.CharField(blank=True, max_length=50)),
                ('machine_pro_emp_name', models.CharField(blank=True, max_length=50)),
                ('machine_pro_emp_contact', models.CharField(blank=True, max_length=50)),
                ('machine_load_capacity', models.CharField(blank=True, max_length=10)),
                ('machine_load_capacity_unit', models.CharField(blank=True, max_length=10)),
                ('machine_power_use_kwatt_per_hour', models.FloatField(blank=True, max_length=10)),
                ('machine_installed_datetime', models.DateField(default=None, null=True)),
                ('machine_start_use_datetime', models.DateField(default=None, null=True)),
                ('machine_hour', models.IntegerField(blank=True, default=None, null=True)),
                ('machine_minute', models.IntegerField(blank=True, default=None, null=True)),
                ('create_by', models.CharField(max_length=20)),
                ('create_date', models.DateField()),
                ('last_update_by', models.CharField(default=None, max_length=20, null=True)),
                ('last_update_date', models.DateField(default=None, null=True)),
                ('machine_image1', models.FileField(blank=True, null=True, upload_to='pictures/')),
                ('machine_image2', models.FileField(blank=True, null=True, upload_to='pictures/')),
                ('machine_image3', models.FileField(blank=True, null=True, upload_to='pictures/')),
                ('machine_image4', models.FileField(blank=True, null=True, upload_to='pictures/')),
                ('machine_image5', models.FileField(blank=True, null=True, upload_to='pictures/')),
                ('machine_document1', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('machine_document2', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('machine_document3', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('machine_document4', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('machine_document5', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('machine_details', models.CharField(blank=True, max_length=256)),
                ('machine_active', models.BooleanField()),
                ('machine_core', models.BooleanField()),
            ],
            options={
                'db_table': 'Machine_master',
                'ordering': ['machine_production_line_code'],
            },
        ),
        migrations.CreateModel(
            name='Machine_and_spare_part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_maintenance_hour', models.IntegerField(blank=True, default=None, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Machine')),
            ],
            options={
                'db_table': 'Machine_and_spare_part',
                'ordering': ['machine', 'spare_part'],
            },
        ),
        migrations.CreateModel(
            name='Machine_type',
            fields=[
                ('mtype_id', models.AutoField(primary_key=True, serialize=False)),
                ('mtype_code', models.CharField(max_length=30)),
                ('mtype_name', models.CharField(max_length=50)),
                ('create_by', models.CharField(max_length=20)),
                ('create_date', models.DateField()),
                ('last_update_by', models.CharField(default=None, max_length=20, null=True)),
                ('last_update_date', models.DateField(default=None, null=True)),
            ],
            options={
                'db_table': 'Machine_type',
            },
        ),
        migrations.CreateModel(
            name='Maintenance_order_detail',
            fields=[
                ('mtn_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_work_start', models.DateTimeField()),
                ('plan_work_finish', models.DateTimeField()),
                ('actual_work_start', models.DateTimeField()),
                ('actual_work_finish', models.DateTimeField()),
                ('remark', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
            ],
            options={
                'db_table': 'Maintenance_order_detail',
            },
        ),
        migrations.CreateModel(
            name='Maintenance_order_head',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_no', models.IntegerField()),
                ('job_date', models.DateField()),
                ('job_assignor_id', models.CharField(max_length=10)),
                ('job_assignee_id', models.CharField(max_length=10)),
                ('job_status', models.BooleanField()),
                ('close_reason', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Maintenance_order_head',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('org_id', models.AutoField(primary_key=True, serialize=False)),
                ('org_code', models.CharField(max_length=25)),
                ('org_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Organization',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Role_management',
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('screen_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('screen_name', models.CharField(max_length=40)),
                ('file_py', models.CharField(max_length=40)),
                ('file_html', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Screen_management',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Site',
            },
        ),
        migrations.CreateModel(
            name='Spare_part_group',
            fields=[
                ('spare_part_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('spare_part_group_code', models.CharField(max_length=30)),
                ('spare_part_group_name', models.CharField(max_length=40)),
                ('create_by', models.CharField(max_length=20)),
                ('create_date', models.DateField()),
                ('last_update_by', models.CharField(default=None, max_length=20, null=True)),
                ('last_update_date', models.DateField(default=None, null=True)),
            ],
            options={
                'db_table': 'Spare_part_group',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('create_by', models.CharField(max_length=10)),
                ('create_date', models.DateTimeField()),
                ('start_date', models.DateField()),
                ('expired_date', models.DateField()),
                ('expired_day', models.IntegerField(default=90)),
                ('update_by', models.CharField(default=None, max_length=10, null=True)),
                ('update_date', models.DateTimeField(default=None, null=True)),
                ('last_login_date', models.DateTimeField(default=None, null=True)),
                ('user_active', models.BooleanField()),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Role')),
            ],
            options={
                'db_table': 'User_management',
            },
        ),
        migrations.CreateModel(
            name='Spare_part_type',
            fields=[
                ('spare_part_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('spare_part_type_code', models.CharField(max_length=30)),
                ('spare_part_type_name', models.CharField(max_length=40)),
                ('create_by', models.CharField(max_length=20)),
                ('create_date', models.DateField()),
                ('last_update_by', models.CharField(default=None, max_length=20, null=True)),
                ('last_update_date', models.DateField(default=None, null=True)),
                ('spare_part_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Spare_part_group')),
            ],
            options={
                'db_table': 'Spare_part_type',
            },
        ),
        migrations.CreateModel(
            name='Spare_part_sub_type',
            fields=[
                ('spare_part_sub_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('spare_part_sub_type_code', models.CharField(max_length=30)),
                ('spare_part_sub_type_name', models.CharField(max_length=40)),
                ('create_by', models.CharField(max_length=20)),
                ('create_date', models.DateField()),
                ('last_update_by', models.CharField(default=None, max_length=20, null=True)),
                ('last_update_date', models.DateField(default=None, null=True)),
                ('spare_part_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Spare_part_type')),
            ],
            options={
                'db_table': 'Spare_part_sub_type',
                'ordering': ['spare_part_type'],
            },
        ),
        migrations.CreateModel(
            name='Spare_part',
            fields=[
                ('spare_part_id', models.AutoField(primary_key=True, serialize=False)),
                ('spare_part_name', models.CharField(blank=True, max_length=40)),
                ('spare_part_code', models.CharField(blank=True, max_length=40)),
                ('spare_part_model', models.CharField(blank=True, max_length=40)),
                ('service_life', models.IntegerField()),
                ('service_plan_life', models.IntegerField()),
                ('create_by', models.CharField(max_length=20)),
                ('create_date', models.DateField()),
                ('last_update_by', models.CharField(default=None, max_length=20, null=True)),
                ('last_update_date', models.DateField(default=None, null=True)),
                ('spare_part_active', models.BooleanField()),
                ('spare_part_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Spare_part_group')),
                ('spare_part_sub_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Spare_part_sub_type')),
                ('spare_part_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Spare_part_type')),
            ],
            options={
                'db_table': 'Spare_part',
            },
        ),
        migrations.CreateModel(
            name='Role_Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_insert', models.CharField(max_length=5)),
                ('permission_update', models.CharField(max_length=5)),
                ('permission_delete', models.CharField(max_length=5)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Role')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Screen')),
            ],
            options={
                'db_table': 'Role_Screen',
                'ordering': ['role'],
            },
        ),
        migrations.AddField(
            model_name='role',
            name='members',
            field=models.ManyToManyField(through='Machine_Management.Role_Screen', to='Machine_Management.Screen'),
        ),
        migrations.CreateModel(
            name='Production_line',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('production_line', models.IntegerField()),
                ('location_building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Building')),
                ('location_floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Floor')),
                ('location_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Site')),
            ],
            options={
                'db_table': 'Production_line',
                'ordering': ['location_site', 'location_building'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_code', models.CharField(max_length=30)),
                ('capacity', models.CharField(max_length=15)),
                ('labour', models.CharField(max_length=10)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Production_line')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='org_line',
            field=models.ManyToManyField(to='Machine_Management.Production_line'),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('level', models.IntegerField()),
                ('parent_menu', models.CharField(default=None, max_length=30, null=True)),
                ('index', models.IntegerField()),
                ('path_url', models.CharField(default=None, max_length=30, null=True)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Screen')),
            ],
            options={
                'db_table': 'Menu_management',
                'ordering': ['level', 'parent_menu', 'index'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance_plan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('gen_date', models.DateField()),
                ('machine_and_spare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Machine_and_spare_part')),
            ],
            options={
                'db_table': 'Maintenance_plan',
            },
        ),
        migrations.CreateModel(
            name='Machine_subtype',
            fields=[
                ('subtype_id', models.AutoField(primary_key=True, serialize=False)),
                ('subtype_code', models.CharField(max_length=30)),
                ('subtype_name', models.CharField(max_length=50)),
                ('create_by', models.CharField(max_length=20)),
                ('create_date', models.DateField()),
                ('last_update_by', models.CharField(default=None, max_length=20, null=True)),
                ('last_update_date', models.DateField(default=None, null=True)),
                ('mch_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Machine_type')),
            ],
            options={
                'db_table': 'Machine_subtype',
            },
        ),
        migrations.CreateModel(
            name='Machine_capacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fg_batch_size', models.IntegerField(blank=True, default=None, null=True)),
                ('fg_batch_time', models.IntegerField(blank=True, default=None, null=True)),
                ('rm_name', models.CharField(max_length=30)),
                ('rm_batch_size', models.IntegerField(blank=True, default=None, null=True)),
                ('rm_unit', models.CharField(max_length=20)),
                ('fg_capacity', models.IntegerField(blank=True, default=None, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Machine')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Product')),
            ],
            options={
                'db_table': 'Machine_capacity',
            },
        ),
        migrations.AddField(
            model_name='machine_and_spare_part',
            name='spare_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Spare_part'),
        ),
        migrations.AddField(
            model_name='machine',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Production_line'),
        ),
        migrations.AddField(
            model_name='machine',
            name='mch_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Machine_type'),
        ),
        migrations.AddField(
            model_name='machine',
            name='sub_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Machine_subtype'),
        ),
        migrations.AddField(
            model_name='floor',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Site'),
        ),
        migrations.AddField(
            model_name='building',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Site'),
        ),
    ]
