# Generated by Django 3.0.8 on 2021-02-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair_and_maintenance_job',
            name='gen_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
