# Generated by Django 3.0.8 on 2020-09-18 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='maintenance_order_detail',
            fields=[
                ('mtn_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_work_start', models.DateTimeField()),
                ('plan_work_finish', models.DateTimeField()),
                ('actual_work_start', models.DateTimeField()),
                ('actual_work_finish', models.DateTimeField()),
                ('remark', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='maintenance_order_head',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_no', models.IntegerField()),
                ('job_date', models.DateField()),
                ('job_assignor_id', models.CharField(max_length=10)),
                ('job_assignee_id', models.CharField(max_length=10)),
                ('job_status', models.BooleanField()),
                ('close_reason', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='maintenance_plan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('gen_date', models.DateField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.maintenance_order_head')),
                ('machine_and_spare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Machine_and_spare_part')),
            ],
        ),
    ]
