# Generated by Django 3.0.8 on 2020-10-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spare_part',
            name='spare_part_brand',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
