# Generated by Django 3.0.8 on 2020-08-19 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Site'),
            preserve_default=False,
        ),
    ]
