# Generated by Django 3.0.8 on 2021-01-26 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repair_notice',
            name='repairer_contact',
        ),
        migrations.AddField(
            model_name='repair_notice',
            name='approve_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Machine_Management.User'),
        ),
        migrations.AddField(
            model_name='repair_notice',
            name='inspect_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Machine_Management.User'),
        ),
        migrations.AlterField(
            model_name='repair_notice',
            name='repairer_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Machine_Management.User'),
        ),
    ]
