# Generated by Django 3.0.8 on 2020-08-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_name',
            field=models.CharField(max_length=50),
        ),
    ]
