# Generated by Django 3.0.8 on 2020-07-30 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='production_line',
            table='Production_line',
        ),
        migrations.AlterModelTable(
            name='role',
            table='Role',
        ),
        migrations.AlterModelTable(
            name='screen',
            table='Screen',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
