# Generated by Django 3.0.8 on 2020-08-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0002_floor_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_code', models.CharField(max_length=30)),
                ('capacity', models.CharField(max_length=15)),
                ('labour', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'ordering': ['site', 'building', 'floor']},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['level', 'parent_menu', 'index']},
        ),
        migrations.AlterModelOptions(
            name='production_line',
            options={'ordering': ['location_site', 'location_building']},
        ),
        migrations.AlterModelOptions(
            name='role_screen',
            options={'ordering': ['role']},
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_code',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_by',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
