# Generated by Django 3.0.8 on 2020-07-30 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0002_auto_20200730_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='role_screen',
            new_name='screen',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_production',
            new_name='production',
        ),
    ]
