# Generated by Django 3.0.8 on 2020-10-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0002_spare_part_spare_part_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='spare_part',
            name='spare_part_serial',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
