# Generated by Django 3.0.8 on 2020-10-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0003_spare_part_spare_part_serial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='production_line',
            options={'ordering': ['location_site', 'location_building', 'production_line']},
        ),
        migrations.RemoveField(
            model_name='spare_part',
            name='spare_part_code',
        ),
        migrations.RemoveField(
            model_name='spare_part',
            name='spare_part_serial',
        ),
    ]
