# Generated by Django 3.0.8 on 2020-07-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0003_auto_20200730_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expired_day',
            field=models.IntegerField(default=90),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_by',
            field=models.CharField(default=None, max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_date',
            field=models.DateTimeField(default=None),
        ),
    ]
