# Generated by Django 3.0.8 on 2020-08-21 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0003_auto_20200821_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Production_line'),
            preserve_default=False,
        ),
    ]
