# Generated by Django 3.0.8 on 2020-08-25 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0003_remove_machine_machine_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='subtype',
            new_name='sub_type',
        ),
        migrations.RenameField(
            model_name='machine_subtype',
            old_name='mchtype',
            new_name='mch_type',
        ),
        migrations.AddField(
            model_name='machine',
            name='mch_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Machine_type'),
            preserve_default=False,
        ),
    ]
