# Generated by Django 3.0.8 on 2021-01-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0003_auto_20210127_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair_notice',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repair_notice',
            name='is_inspect',
            field=models.BooleanField(default=False),
        ),
    ]
