# Generated by Django 3.0.8 on 2021-01-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0004_auto_20210127_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair_notice',
            name='is_approve',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='repair_notice',
            name='is_cancel',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='repair_notice',
            name='is_inspect',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
