# Generated by Django 3.0.8 on 2020-10-20 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0004_auto_20201020_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spare_part',
            name='spare_part_brand',
        ),
    ]
