# Generated by Django 3.0.8 on 2020-09-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0005_remove_maintenance_plan_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_hour',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='machine_and_spare_part',
            name='last_maintenance_hour',
            field=models.IntegerField(blank=True),
        ),
    ]
