# Generated by Django 3.0.8 on 2020-08-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0005_auto_20200826_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_brand',
            field=models.CharField(blank=True, default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_capacity_measure_unit',
            field=models.CharField(blank=True, default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_capacity_per_minute',
            field=models.CharField(blank=True, default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_emp_id_response',
            field=models.CharField(blank=True, default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_location_id',
            field=models.CharField(blank=True, default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_model',
            field=models.CharField(blank=True, default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_name',
            field=models.CharField(blank=True, default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_power_use_watt_per_hour',
            field=models.CharField(blank=True, default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_supplier_code',
            field=models.CharField(blank=True, default=1, max_length=10),
            preserve_default=False,
        ),
    ]
