# Generated by Django 3.0.8 on 2020-07-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0005_auto_20200730_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='update_by',
            field=models.CharField(default=None, max_length=6, null=True),
        ),
    ]
