# Generated by Django 3.0.8 on 2020-08-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0006_auto_20200826_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='screen',
            name='file_html',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='screen',
            name='file_py',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_name',
            field=models.CharField(max_length=40),
        ),
    ]
