# Generated by Django 3.0.8 on 2020-07-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0006_auto_20200730_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
