# Generated by Django 3.0.8 on 2020-10-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0006_spare_part_spare_part_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='spare_part',
            name='spare_part_detail',
            field=models.TextField(blank=True),
        ),
    ]
