# Generated by Django 3.0.8 on 2021-02-01 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0006_auto_20210129_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance_job',
            name='job_gen_user_id',
        ),
        migrations.AddField(
            model_name='maintenance_job',
            name='job_gen_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Machine_Management.User'),
        ),
        migrations.AlterField(
            model_name='maintenance_job',
            name='job_assign_user_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Machine_Management.User'),
        ),
        migrations.AlterField(
            model_name='maintenance_job',
            name='job_response_user_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Machine_Management.User'),
        ),
    ]
