# Generated by Django 3.0.8 on 2020-11-04 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0007_spare_part_spare_part_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine_sparepart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_mtnchng_hour', models.IntegerField(blank=True, default=None)),
                ('last_mtnchk_hour', models.IntegerField(blank=True, default=None)),
                ('mtnchng_life_hour', models.IntegerField(blank=True, default=None)),
                ('mtnchk_life_hour', models.IntegerField(blank=True, default=None)),
                ('next_mtnchng_hour', models.IntegerField(blank=True, default=None)),
                ('next_mtnchk_hour', models.IntegerField(blank=True, default=None)),
                ('last_mtnchng_job_id', models.IntegerField(blank=True, default=None)),
                ('last_mtnchk_job_id', models.IntegerField(blank=True, default=None)),
                ('gen_mtnchng_date', models.IntegerField(blank=True, default=None)),
                ('gen_mtnchk_date', models.IntegerField(blank=True, default=None)),
                ('warning_hour', models.IntegerField(blank=True, default=None)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Machine')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Spare_part')),
            ],
            options={
                'db_table': 'Machine_Sparepart',
                'ordering': ['machine', 'spare_part'],
            },
        ),
        migrations.AlterField(
            model_name='maintenance_plan',
            name='machine_and_spare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Machine_sparepart'),
        ),
        migrations.DeleteModel(
            name='Machine_and_spare_part',
        ),
    ]
