# Generated by Django 3.0.8 on 2020-09-21 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0007_auto_20200921_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine_capacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fg_batch_size', models.IntegerField(blank=True, default=None, null=True)),
                ('fg_batch_time', models.IntegerField(blank=True, default=None, null=True)),
                ('rm_name', models.CharField(max_length=30)),
                ('rm_batch_size', models.IntegerField(blank=True, default=None, null=True)),
                ('rm_unit', models.CharField(max_length=20)),
                ('fg_capacity', models.FloatField(blank=True, default=None, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Machine')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Product')),
            ],
            options={
                'db_table': 'Machine_capacity',
            },
        ),
    ]
