# Generated by Django 3.0.8 on 2021-02-01 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0007_auto_20210201_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance_job',
            old_name='job_assign_user_id',
            new_name='job_assign_user',
        ),
        migrations.RenameField(
            model_name='maintenance_job',
            old_name='job_response_user_id',
            new_name='job_response_user',
        ),
    ]
