# Generated by Django 3.0.8 on 2020-09-09 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0007_auto_20200827_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spare_part_type',
            fields=[
                ('spare_part_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('spare_part_type_code', models.CharField(max_length=30)),
                ('spare_part_type_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['machine_production_line_code']},
        ),
        migrations.CreateModel(
            name='Spare_part_sub_type',
            fields=[
                ('spare_part_sub_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('spare_part_sub_type_code', models.CharField(max_length=30)),
                ('spare_part_sub_type_name', models.CharField(max_length=40)),
                ('spare_part_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Spare_part_type')),
            ],
        ),
        migrations.CreateModel(
            name='Spare_part',
            fields=[
                ('spare_part_id', models.AutoField(primary_key=True, serialize=False)),
                ('spare_part_name', models.CharField(blank=True, max_length=40)),
                ('spare_part_code', models.CharField(blank=True, max_length=40)),
                ('spare_part_model', models.CharField(blank=True, max_length=40)),
                ('service_life', models.IntegerField()),
                ('service_plan_life', models.IntegerField()),
                ('spare_part_sub_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Spare_part_sub_type')),
                ('spare_part_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Spare_part_type')),
            ],
        ),
    ]
