# Generated by Django 3.0.8 on 2020-11-04 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0008_auto_20201104_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(max_length=20)),
                ('job_gen_date', models.DateField()),
                ('job_assign_user_id', models.CharField(max_length=20)),
                ('job_response_user_id', models.CharField(max_length=20)),
                ('job_assign_date', models.DateField()),
                ('jon_mtn_type', models.CharField(max_length=20)),
                ('job_result_type', models.CharField(max_length=20)),
                ('job_result_description', models.TextField()),
                ('job_fix_plan_hour', models.IntegerField()),
                ('job_mch_hour', models.IntegerField()),
                ('job_plan_hour', models.IntegerField()),
                ('job_report_date', models.DateField()),
                ('job_gen_user_id', models.CharField(max_length=20)),
                ('job_machine_sparepart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Machine_sparepart')),
            ],
        ),
        migrations.DeleteModel(
            name='Maintenance_order_detail',
        ),
        migrations.DeleteModel(
            name='Maintenance_order_head',
        ),
        migrations.DeleteModel(
            name='Maintenance_plan',
        ),
    ]
