# Generated by Django 3.0.8 on 2020-08-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0008_auto_20200803_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production_line',
            name='id',
        ),
        migrations.AlterField(
            model_name='production_line',
            name='line_id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
