# Generated by Django 3.0.8 on 2020-09-09 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0008_auto_20200909_1317'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='spare_part',
            table='Spare_part',
        ),
        migrations.AlterModelTable(
            name='spare_part_sub_type',
            table='Spare_part_sub_type',
        ),
        migrations.AlterModelTable(
            name='spare_part_type',
            table='Spare_part_type',
        ),
    ]
