# Generated by Django 3.0.8 on 2020-09-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0008_machine_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_brand',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_emp_id_response',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_model',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_supplier_code',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
