# Generated by Django 3.0.8 on 2020-08-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0009_auto_20200803_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='production_line',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='production_line',
            name='line_id',
            field=models.CharField(max_length=6),
        ),
    ]
