# Generated by Django 3.0.8 on 2020-09-10 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0009_auto_20200909_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spare_part_sub_type',
            options={'ordering': ['spare_part_type']},
        ),
        migrations.AddField(
            model_name='machine',
            name='spare_part',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Spare_part'),
            preserve_default=False,
        ),
    ]
