# Generated by Django 3.0.8 on 2020-11-06 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0009_auto_20201104_1632'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Maintenance',
            new_name='Maintenance_job',
        ),
        migrations.AlterModelTable(
            name='maintenance_job',
            table='maintenance_job',
        ),
    ]
