# Generated by Django 3.0.8 on 2021-02-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0009_auto_20210204_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repair_notice',
            name='job1',
        ),
        migrations.RemoveField(
            model_name='repair_notice',
            name='job2',
        ),
        migrations.RemoveField(
            model_name='repair_notice',
            name='job3',
        ),
        migrations.RemoveField(
            model_name='repair_notice',
            name='job4',
        ),
        migrations.RemoveField(
            model_name='repair_notice',
            name='job5',
        ),
        migrations.RemoveField(
            model_name='repair_notice',
            name='spare_part_1',
        ),
        migrations.RemoveField(
            model_name='repair_notice',
            name='spare_part_2',
        ),
        migrations.RemoveField(
            model_name='repair_notice',
            name='spare_part_3',
        ),
        migrations.RemoveField(
            model_name='repair_notice',
            name='spare_part_4',
        ),
        migrations.RemoveField(
            model_name='repair_notice',
            name='spare_part_5',
        ),
        migrations.AddField(
            model_name='repair_notice',
            name='maintenance_jobs',
            field=models.ManyToManyField(to='Machine_Management.Maintenance_job'),
        ),
        migrations.AlterField(
            model_name='repair_notice',
            name='repair_no',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
