# Generated by Django 3.0.8 on 2020-09-25 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0010_auto_20200925_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='machine_power_use_watt_per_hour',
            new_name='machine_power_use_kwatt_per_hour',
        ),
    ]
