# Generated by Django 3.0.8 on 2021-02-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0010_auto_20210208_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance_job',
            name='job_gen_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='maintenance_job',
            name='job_no',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
