# Generated by Django 3.0.8 on 2020-09-10 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0010_auto_20200910_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='spare_part',
        ),
    ]
