# Generated by Django 3.0.8 on 2020-11-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0010_auto_20201106_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine_sparepart',
            name='gen_mtnchk_date',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='machine_sparepart',
            name='gen_mtnchng_date',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='machine_sparepart',
            name='last_mtnchk_hour',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='machine_sparepart',
            name='last_mtnchk_job_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='machine_sparepart',
            name='last_mtnchng_hour',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='machine_sparepart',
            name='last_mtnchng_job_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='machine_sparepart',
            name='mtnchk_life_hour',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='machine_sparepart',
            name='mtnchng_life_hour',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='machine_sparepart',
            name='next_mtnchk_hour',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='machine_sparepart',
            name='next_mtnchng_hour',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='machine_sparepart',
            name='warning_hour',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
