# Generated by Django 3.0.8 on 2020-11-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0011_auto_20201106_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine_sparepart',
            name='gen_mtnchk_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='machine_sparepart',
            name='gen_mtnchng_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
