# Generated by Django 3.0.8 on 2020-09-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0011_remove_machine_spare_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='spare_parts',
            field=models.ManyToManyField(to='Machine_Management.Spare_part'),
        ),
    ]
