# Generated by Django 3.0.8 on 2021-02-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0011_auto_20210209_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair_notice',
            name='close_remark',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='repair_notice',
            name='is_close',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
