# Generated by Django 3.0.8 on 2020-11-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0012_auto_20201109_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine_sparepart',
            name='gen_mtnchk_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
