# Generated by Django 3.0.8 on 2020-09-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0012_machine_spare_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='create_by',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='create_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='last_update_by',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='last_update_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_by',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
