# Generated by Django 3.0.8 on 2020-09-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0012_auto_20200925_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_document1',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_document2',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_document3',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_document4',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_document5',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
