# Generated by Django 3.0.8 on 2020-11-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0013_auto_20201110_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance_job',
            old_name='job_machine_sparepart_id',
            new_name='job_mch_sp',
        ),
        migrations.AlterField(
            model_name='maintenance_job',
            name='job_assign_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance_job',
            name='job_assign_user_id',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance_job',
            name='job_fix_plan_hour',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance_job',
            name='job_gen_user_id',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance_job',
            name='job_mch_hour',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance_job',
            name='job_plan_hour',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance_job',
            name='job_report_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance_job',
            name='job_response_user_id',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance_job',
            name='job_result_description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance_job',
            name='job_result_type',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance_job',
            name='jon_mtn_type',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
