# Generated by Django 3.0.8 on 2020-08-03 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0013_auto_20200803_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production_line',
            name='id',
        ),
        migrations.RemoveField(
            model_name='production_line',
            name='machine_code',
        ),
        migrations.RemoveField(
            model_name='production_line',
            name='machine_name',
        ),
        migrations.RemoveField(
            model_name='production_line',
            name='machine_type',
        ),
        migrations.AlterField(
            model_name='production_line',
            name='line_id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_code', models.CharField(max_length=10)),
                ('machine_name', models.CharField(max_length=20)),
                ('machine_type', models.CharField(max_length=10)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Production_line')),
            ],
            options={
                'db_table': 'Machine',
            },
        ),
    ]
