# Generated by Django 3.0.8 on 2020-09-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0013_auto_20200928_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_document1',
            field=models.FileField(blank=True, null=True, upload_to='documents/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_document2',
            field=models.FileField(blank=True, null=True, upload_to='documents/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_document3',
            field=models.FileField(blank=True, null=True, upload_to='documents/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_document4',
            field=models.FileField(blank=True, null=True, upload_to='documents/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_document5',
            field=models.FileField(blank=True, null=True, upload_to='documents/<django.db.models.fields.CharField>/'),
        ),
    ]
