# Generated by Django 3.0.8 on 2020-09-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0013_auto_20200914_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='spare_part',
            name='create_by',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spare_part',
            name='create_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spare_part',
            name='last_update_by',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='spare_part',
            name='last_update_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='spare_part_sub_type',
            name='create_by',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spare_part_sub_type',
            name='create_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spare_part_sub_type',
            name='last_update_by',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='spare_part_sub_type',
            name='last_update_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='spare_part_type',
            name='create_by',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spare_part_type',
            name='create_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spare_part_type',
            name='last_update_by',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='spare_part_type',
            name='last_update_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
