# Generated by Django 3.0.8 on 2020-09-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0014_auto_20200914_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='machine_location_id',
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_details',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_document1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_document2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_document3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_document4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_document5',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_image1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_image2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_image3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_image4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_image5',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='user_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
