# Generated by Django 3.0.8 on 2020-11-11 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0014_auto_20201110_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance_job',
            old_name='jon_mtn_type',
            new_name='job_mtn_type',
        ),
    ]
