# Generated by Django 3.0.8 on 2020-08-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0014_auto_20200803_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_name',
            field=models.CharField(max_length=18),
        ),
    ]
