# Generated by Django 3.0.8 on 2020-11-13 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0015_auto_20201111_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='machine_minute',
            new_name='machine_hour_last_update',
        ),
    ]
