# Generated by Django 3.0.8 on 2020-09-15 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0015_auto_20200915_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='spare_parts',
        ),
        migrations.CreateModel(
            name='Machine_and_spare_part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Machine')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Spare_part')),
            ],
            options={
                'db_table': 'Machine_and_spare_part',
                'ordering': ['machine'],
            },
        ),
    ]
