# Generated by Django 3.0.8 on 2020-08-03 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0016_auto_20200803_0940'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Machine',
        ),
    ]
