# Generated by Django 3.0.8 on 2020-11-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0016_auto_20201113_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='machine_hour_update_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
