# Generated by Django 3.0.8 on 2020-11-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0017_machine_machine_hour_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_hour_update_date',
            field=models.DateField(default=None),
        ),
    ]
