# Generated by Django 3.0.8 on 2020-09-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0017_remove_machine_type_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='spare_part_type',
            name='spare_part_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
