# Generated by Django 3.0.8 on 2020-09-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0018_spare_part_type_spare_part_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spare_part_type',
            name='spare_part_active',
        ),
        migrations.AddField(
            model_name='spare_part',
            name='spare_part_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
