# Generated by Django 3.0.8 on 2020-11-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0018_auto_20201123_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_hour_update_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
