# Generated by Django 3.0.8 on 2020-12-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0019_auto_20201123_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance_job',
            name='after_repair',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='maintenance_job',
            name='corrective_action',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='maintenance_job',
            name='equipment_code',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='maintenance_job',
            name='equipment_detail',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='maintenance_job',
            name='equipment_note',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='maintenance_job',
            name='equipment_quantity',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='maintenance_job',
            name='estimate_cost',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='maintenance_job',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenance_job',
            name='job_remark',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='maintenance_job',
            name='job_status',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='maintenance_job',
            name='problem_cause',
            field=models.TextField(default=None, null=True),
        ),
    ]
