# Generated by Django 3.0.8 on 2020-08-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0019_auto_20200803_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='file_html',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_name',
            field=models.CharField(max_length=20),
        ),
    ]
