# Generated by Django 3.0.8 on 2020-12-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0020_auto_20201222_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance_job',
            name='job_approve_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
