# Generated by Django 3.0.8 on 2020-08-04 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0020_auto_20200803_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='screen',
        ),
        migrations.CreateModel(
            name='Role_Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_insert', models.CharField(max_length=5)),
                ('permission_update', models.CharField(max_length=5)),
                ('permission_delete', models.CharField(max_length=5)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Role')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Screen')),
            ],
            options={
                'db_table': 'Role_Screen',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='members',
            field=models.ManyToManyField(through='Machine_Management.Role_Screen', to='Machine_Management.Screen'),
        ),
    ]
