# Generated by Django 3.0.8 on 2020-08-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0021_auto_20200804_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='machine_brand',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_capacity_measure_unit',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_capacity_per_minute',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_emp_id_response',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_installed_datetime',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_location_id',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_model',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_power_use_watt_per_hour',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_start_use_datetime',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_supplier_code',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='serial_id',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_code',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_name',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterModelTable(
            name='machine',
            table='Machine_master',
        ),
    ]
