# Generated by Django 3.0.8 on 2020-12-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0021_maintenance_job_job_approve_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance_job',
            old_name='equipment_code',
            new_name='equipment_code1',
        ),
        migrations.RenameField(
            model_name='maintenance_job',
            old_name='equipment_detail',
            new_name='equipment_detail1',
        ),
        migrations.RenameField(
            model_name='maintenance_job',
            old_name='equipment_note',
            new_name='equipment_note1',
        ),
        migrations.RenameField(
            model_name='maintenance_job',
            old_name='equipment_quantity',
            new_name='equipment_quantity1',
        ),
        migrations.AddField(
            model_name='maintenance_job',
            name='equipment_code2',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='maintenance_job',
            name='equipment_code3',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='maintenance_job',
            name='equipment_detail2',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='maintenance_job',
            name='equipment_detail3',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='maintenance_job',
            name='equipment_note2',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='maintenance_job',
            name='equipment_note3',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='maintenance_job',
            name='equipment_quantity2',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='maintenance_job',
            name='equipment_quantity3',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
