# Generated by Django 3.0.8 on 2020-12-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0023_repair_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair_notice',
            name='notification_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='repair_notice',
            name='use_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
