# Generated by Django 3.0.8 on 2020-08-10 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0025_auto_20200806_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('level', models.IntegerField(max_length=2)),
                ('parent_menu', models.CharField(default=None, max_length=30, null=True)),
                ('index', models.IntegerField(max_length=2)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Machine_Management.Screen')),
            ],
        ),
    ]
