# Generated by Django 3.0.8 on 2020-08-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0026_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='menu',
            name='level',
            field=models.IntegerField(),
        ),
    ]
