# Generated by Django 3.0.8 on 2020-12-29 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0026_repair_notice_spare_part_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair_notice',
            name='spare_part_2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Machine_Management.Spare_part'),
        ),
        migrations.AlterField(
            model_name='repair_notice',
            name='spare_part_1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Machine_Management.Spare_part'),
        ),
    ]
