# Generated by Django 3.0.8 on 2021-01-04 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0027_auto_20201229_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair_notice',
            name='spare_part_3',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Machine_Management.Spare_part'),
        ),
        migrations.AddField(
            model_name='repair_notice',
            name='spare_part_4',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Machine_Management.Spare_part'),
        ),
        migrations.AddField(
            model_name='repair_notice',
            name='spare_part_5',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Machine_Management.Spare_part'),
        ),
    ]
