# Generated by Django 3.0.8 on 2020-08-10 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0027_auto_20200810_0825'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menu',
            table='Menu',
        ),
    ]
