# Generated by Django 3.0.8 on 2021-01-04 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0028_auto_20210104_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair_notice',
            name='job1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Machine_Management.Maintenance_job'),
        ),
        migrations.AddField(
            model_name='repair_notice',
            name='job2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Machine_Management.Maintenance_job'),
        ),
        migrations.AddField(
            model_name='repair_notice',
            name='job3',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Machine_Management.Maintenance_job'),
        ),
        migrations.AddField(
            model_name='repair_notice',
            name='job4',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Machine_Management.Maintenance_job'),
        ),
        migrations.AddField(
            model_name='repair_notice',
            name='job5',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Machine_Management.Maintenance_job'),
        ),
    ]
