# Generated by Django 3.0.8 on 2020-08-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0028_auto_20200810_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='path_url',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
