# Generated by Django 3.0.8 on 2020-08-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0029_menu_path_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_code',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='serial_id',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='menu',
            table='Menu_management',
        ),
        migrations.AlterModelTable(
            name='role',
            table='Role_management',
        ),
        migrations.AlterModelTable(
            name='screen',
            table='Screen_management',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User_management',
        ),
    ]
