# Generated by Django 3.0.8 on 2021-01-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0029_auto_20210104_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance_job',
            name='job_no',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='repair_notice',
            name='repair_no',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
