# Generated by Django 3.0.8 on 2021-01-05 13:21

import Machine_Management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0030_auto_20210105_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance_job',
            name='job_no',
            field=models.CharField(default=Machine_Management.models.randomJobOrder, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='repair_notice',
            name='repair_no',
            field=models.CharField(default=Machine_Management.models.randomRepairOrder, max_length=20, unique=True),
        ),
    ]
