# Generated by Django 3.0.8 on 2021-01-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0031_auto_20210105_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare_part',
            name='service_life',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='service_plan_life',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='spare_part_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='spare_part_detail',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
