# Generated by Django 3.0.8 on 2021-01-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0032_auto_20210120_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare_part',
            name='service_life',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='service_plan_life',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
