# Generated by Django 3.0.8 on 2021-01-21 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_Management', '0035_auto_20210121_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='create_by',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='update_by',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
